steps:
# running docker-compose
- name: 'docker/compose:1.26.2'
  args: ['up', '-d']
- name: 'composer'
  args: ['composer','install'] 
  # args: ['exec', 'app', 'composer','install'] 
- name: 'ubuntu'
  args: ['cp','.env.example','.env']
  # run: php -r "file_exists('.env') || copy('.env.example', '.env');"
- name: 'php'
  args: ['php','artisan','key:generate']
- name: 'php'
  args: ['php','artisan','migrate']
- name: 'php'
  args: ['php-fpm']