steps:
# running docker-compose
#STEP 1
- id: "Step 01 - Realizando composer up"
  name: 'docker/compose:1.26.2'
  args: ['up', '-d']

#STEP 2
- id: "Step 02 - Rodando composer"
  name: 'docker/compose:1.26.2'
  args: ['exec','-d','app','composer','install']

#STEP 3
- id: "Step 03 - Copiando o .env.example para .env"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-d','app', 'cp','.env.example','.env']
#STEP 4
- id: "Step 04 - Key Generate"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-d','app','php','artisan','key:generate']
#STEP 5
- id: "Step 05 - Artisan Migrate"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-d','app', 'php','artisan','migrate']
#STEP 6
- id: "Step 06 - PHP-FPM"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-d','app','php-fpm']




# #STEP 2
# - name: 'composer'
#   args: ['composer','install'] 
# #STEP 3
# - name: 'ubuntu'
#   args: ['cp','.env.example','.env']
# #STEP 3
# - name: 'php:7.3.6-fpm-alpine3.9'
#   args: ['php','artisan','key:generate']
# #STEP 4
# - name: 'php:7.3.6-fpm-alpine3.9'
#   args: ['php','artisan','migrate']
# #STEP 5
# - name: 'php:7.3.6-fpm-alpine3.9'
#   args: ['php-fpm']