steps:
# running docker-compose
- name: 'docker/compose:1.26.2'
  args: ['up', '-d']
#   #STEP 2
# - name: 'docker'
#   args: ['exec', 'app', 'composer','install']
- name: 'composer'
  args: ['composer','install'] 
  # args: ['exec', 'app', 'composer','install'] 
# - name: 'ubuntu'
#   args: ['cp','.env.example','.env']
- name: 'docker'
  args: ['exec', 'bash', 'cp','.env.example','.env']
  # run: php -r "file_exists('.env') || copy('.env.example', '.env');"
- name: 'php:7.3.6-fpm-alpine3.9'
  args: ['php','artisan','key:generate']
- name: 'php:7.3.6-fpm-alpine3.9'
  args: ['php','artisan','migrate']
- name: 'php:7.3.6-fpm-alpine3.9'
  args: ['php-fpm']